repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: black
        name: black
        entry: .venv/Scripts/python.exe -m black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: .venv/Scripts/python.exe -m isort
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: .venv/Scripts/python.exe -m pylint
        args: [--rcfile=pyproject.toml]
        language: system
        files: ^src/.*\.py$
        types: [python]
